CREATE TABLE `certificates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`clientId` int NOT NULL,
	`installationId` int NOT NULL,
	`status` enum('draft','completed','archived') NOT NULL DEFAULT 'draft',
	`certificateNumber` varchar(50),
	`installationType` varchar(100),
	`supplyVoltage` int,
	`installedPower` int,
	`phases` int,
	`diLength` decimal(8,2),
	`diCableSection` decimal(8,2),
	`diCableMaterial` varchar(10),
	`diCableInsulation` varchar(50),
	`boardLocation` varchar(255),
	`igaRating` int,
	`idSensitivity` int,
	`overvoltageProtection` boolean,
	`earthResistance` decimal(8,2),
	`insulationResistance` decimal(8,2),
	`continuityContinuity` decimal(8,2),
	`rcdTestCurrent` int,
	`rcdTestTime` int,
	`observations` text,
	`mermaidDiagram` text,
	`pdfUrl` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `certificates_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `circuits` (
	`id` int AUTO_INCREMENT NOT NULL,
	`certificateId` int NOT NULL,
	`circuitNumber` varchar(20) NOT NULL,
	`circuitName` varchar(255) NOT NULL,
	`circuitType` varchar(100),
	`installedPower` int,
	`length` decimal(8,2),
	`cableSection` decimal(8,2),
	`cableMaterial` varchar(10),
	`cableInsulation` varchar(50),
	`cableCores` int,
	`mcbRating` int,
	`mcbCurve` varchar(10),
	`rcdRequired` boolean,
	`rcdRating` int,
	`loadDescription` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `circuits_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `clients` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`type` enum('person','company') NOT NULL,
	`name` varchar(255) NOT NULL,
	`dniNif` varchar(20),
	`email` varchar(255),
	`phone` varchar(20),
	`address` text,
	`postalCode` varchar(10),
	`city` varchar(100),
	`province` varchar(100),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `clients_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `installations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`clientId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`type` varchar(100),
	`address` text,
	`postalCode` varchar(10),
	`city` varchar(100),
	`province` varchar(100),
	`cadastralReference` varchar(50),
	`cups` varchar(50),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `installations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`fullName` varchar(255),
	`companyName` varchar(255),
	`cifNif` varchar(20),
	`installerNumber` varchar(50),
	`installerCategory` varchar(50),
	`autonomousCommunity` varchar(50),
	`phone` varchar(20),
	`address` text,
	`postalCode` varchar(10),
	`city` varchar(100),
	`province` varchar(100),
	`avatarUrl` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `profiles_id` PRIMARY KEY(`id`),
	CONSTRAINT `profiles_userId_unique` UNIQUE(`userId`)
);
--> statement-breakpoint
CREATE TABLE `subscriptions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`stripeCustomerId` varchar(255),
	`stripeSubscriptionId` varchar(255),
	`stripePriceId` varchar(255),
	`plan` enum('free','pro','enterprise') NOT NULL DEFAULT 'free',
	`status` enum('active','canceled','past_due') NOT NULL DEFAULT 'active',
	`currentPeriodStart` timestamp,
	`currentPeriodEnd` timestamp,
	`certificatesLimit` int DEFAULT 1,
	`certificatesUsed` int DEFAULT 0,
	`cancelAtPeriodEnd` boolean DEFAULT false,
	`canceledAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `subscriptions_id` PRIMARY KEY(`id`),
	CONSTRAINT `subscriptions_userId_unique` UNIQUE(`userId`)
);
